### ISSUE TITLE
Create a Validation CR

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/mpas-product-controller#16]
The CR should run validation for a specific pull request.

Tentative structure:

```yaml
apiVersion: mpas.ocm.software/v1alpha1
kind: Validation
metadata:
  name: podinfo
  namespace: mpas-sample-project
spec:
  pullRequest: 1 # id of the pull request
# TODO: This should come from the project.
#  repositroyRef:
#    name: podinfo-repo
#    namespace: mpas-system
  validationRules:
    sourceRef: ?? # probably the snapshot where the validation rules can be fetched from?
  interval: 5s
  gitRepositroyRef:
    name: values-yaml-git-repo
  serviceAccountName: mpas-sample-project
```

This should watch the git repository source and run validation on the values yaml file.
